// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_oXFAFaYDlyDWG7giUv4F0tDAhV3FaE',
    appId: '1:516061970152:web:0f44d33b68551c59b0d35d',
    messagingSenderId: '516061970152',
    projectId: 'desishotapp',
    authDomain: 'desishotapp.firebaseapp.com',
    storageBucket: 'desishotapp.firebasestorage.app',
    measurementId: 'G-N8DXVSKDZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUkPk6mwIa0BJrIWlIdl1YWUesDcSOwt0',
    appId: '1:516061970152:android:5ca1704578ce2be0b0d35d',
    messagingSenderId: '516061970152',
    projectId: 'desishotapp',
    storageBucket: 'desishotapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC74hkqve6rAhcmzP5tSDWqhDw093zBSg4',
    appId: '1:516061970152:ios:435b9cd28b494a73b0d35d',
    messagingSenderId: '516061970152',
    projectId: 'desishotapp',
    storageBucket: 'desishotapp.firebasestorage.app',
    iosClientId: '516061970152-eujpbcnsdcdvq50nuv29o0n39u8hqtl4.apps.googleusercontent.com',
    iosBundleId: 'com.example.desishotApp',
  );
}
